name: Tox Linter

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Tox
        run: pip install tox

      - name: Run tox linter
        run: tox -c tox.ini